server {
    listen 80;
    server_name localhost;

    root /root/net_port/web/frontend_net_port;

	location ~ ^/api* {
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;

	    proxy_pass http://localhost:8080;
            proxy_set_header Host $http_host;
            proxy_redirect off;
	}

    location ~ ^/authentication {                                                  
        proxy_set_header X-Real-IP $remote_addr;                         
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;     
        proxy_set_header X-NginX-Proxy true;                             
                                                                            
        proxy_pass http://localhost:8080;                                
        proxy_set_header Host $http_host;                               
        proxy_redirect off;                                             
    }  

    location ~ ^/authentication/oauth* {                                                  
        proxy_set_header X-Real-IP $remote_addr;                         
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;     
        proxy_set_header X-NginX-Proxy true;                             
                                                                            
        proxy_pass http://localhost:8080;                                
        proxy_set_header Host $http_host;                               
        proxy_redirect off;                                             
    }

    location ~ ^/roles {                                                  
        proxy_set_header X-Real-IP $remote_addr;                         
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;     
        proxy_set_header X-NginX-Proxy true;                             
                                                                            
        proxy_pass http://localhost:8080;                                
        proxy_set_header Host $http_host;                               
        proxy_redirect off;                                             
    }
}
